CREATE TABLE product_option_stock_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_option_id BIGINT NOT NULL REFERENCES product_options(id) ON DELETE RESTRICT,
    stock_item_id BIGINT NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
    quantity_per_selection NUMERIC(15, 3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_product_option_stock_links_quantity CHECK (quantity_per_selection > 0),
    CONSTRAINT chk_product_option_stock_links_timestamps CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_product_option_stock_links_active_option
    ON product_option_stock_links (product_option_id) WHERE active = TRUE;
CREATE INDEX idx_product_option_stock_links_stock_item
    ON product_option_stock_links (stock_item_id, active);
