CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date DATE NOT NULL,
    description VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL,
    supplier VARCHAR(160),
    value_mode VARCHAR(20) NOT NULL,
    quantity NUMERIC(15, 3),
    unit VARCHAR(30),
    unit_price NUMERIC(12, 2),
    total_amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    stock_item_id BIGINT REFERENCES stock_items(id) ON DELETE RESTRICT,
    stock_quantity NUMERIC(15, 3),
    stock_movement_id BIGINT UNIQUE REFERENCES stock_movements(id) ON DELETE RESTRICT,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_expenses_description CHECK (btrim(description) <> ''),
    CONSTRAINT chk_expenses_supplier CHECK (supplier IS NULL OR btrim(supplier) <> ''),
    CONSTRAINT chk_expenses_category CHECK (category IN (
        'STOCK_PURCHASE', 'FOOD', 'BEVERAGE', 'PACKAGING', 'CLEANING',
        'MAINTENANCE', 'UTILITIES', 'TRANSPORT', 'SERVICES', 'TAX', 'OTHER'
    )),
    CONSTRAINT chk_expenses_value_mode CHECK (value_mode IN ('DIRECT', 'DETAILED')),
    CONSTRAINT chk_expenses_unit CHECK (
        unit IS NULL OR unit IN ('KG', 'G', 'L', 'ML', 'UN', 'CX', 'PACKAGE', 'TRAY')
    ),
    CONSTRAINT chk_expenses_values CHECK (
        total_amount > 0
        AND (
            (value_mode = 'DIRECT' AND quantity IS NULL AND unit IS NULL AND unit_price IS NULL)
            OR
            (value_mode = 'DETAILED' AND quantity > 0 AND unit IS NOT NULL AND unit_price > 0
                AND total_amount = round(quantity * unit_price, 2))
        )
    ),
    CONSTRAINT chk_expenses_payment_method CHECK (payment_method IN (
        'CASH', 'PIX', 'DEBIT_CARD', 'CREDIT_CARD', 'BANK_TRANSFER', 'BOLETO', 'OTHER'
    )),
    CONSTRAINT chk_expenses_status CHECK (status IN ('PAID', 'PENDING')),
    CONSTRAINT chk_expenses_stock_entry CHECK (
        (stock_item_id IS NULL AND stock_quantity IS NULL AND stock_movement_id IS NULL)
        OR
        (stock_item_id IS NOT NULL AND stock_quantity > 0 AND stock_movement_id IS NOT NULL)
    ),
    CONSTRAINT chk_expenses_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_expenses_date ON expenses (expense_date DESC, id DESC);
CREATE INDEX idx_expenses_filters ON expenses (category, status, payment_method, expense_date DESC);
CREATE INDEX idx_expenses_stock_item ON expenses (stock_item_id, expense_date DESC)
    WHERE stock_item_id IS NOT NULL;
CREATE INDEX idx_expenses_created_by ON expenses (created_by_user_id, created_at DESC);
