-- HubOn simplified schema proposal.
-- Documentation only: do not execute before the implementation is authorized.
-- Target database: PostgreSQL.

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),

    CONSTRAINT chk_roles_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT uq_roles_name
        UNIQUE (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_users_email_not_blank
        CHECK (btrim(email) <> ''),
    CONSTRAINT chk_users_password_not_blank
        CHECK (btrim(password) <> ''),
    CONSTRAINT chk_users_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_users_email_ci
    ON users (lower(email));

CREATE INDEX idx_users_active_name
    ON users (active, name);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_role
    ON user_roles (role_id, user_id);

CREATE TABLE restaurant_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER NOT NULL,
    label VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_restaurant_tables_number
        UNIQUE (number),
    CONSTRAINT chk_restaurant_tables_number
        CHECK (number > 0),
    CONSTRAINT chk_restaurant_tables_label
        CHECK (label IS NULL OR btrim(label) <> ''),
    CONSTRAINT chk_restaurant_tables_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_restaurant_tables_active_number
    ON restaurant_tables (active, number);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_categories_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_categories_display_order
        CHECK (display_order >= 0),
    CONSTRAINT chk_categories_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_categories_name_ci
    ON categories (lower(name));

CREATE INDEX idx_categories_catalog_order
    ON categories (active, display_order, name);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(12, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT chk_products_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_products_description
        CHECK (description IS NULL OR btrim(description) <> ''),
    CONSTRAINT chk_products_price
        CHECK (price >= 0),
    CONSTRAINT chk_products_display_order
        CHECK (display_order >= 0),
    CONSTRAINT chk_products_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_products_category_name_ci
    ON products (category_id, lower(name))
    WHERE category_id IS NOT NULL;

CREATE UNIQUE INDEX uq_products_uncategorized_name_ci
    ON products (lower(name))
    WHERE category_id IS NULL;

CREATE INDEX idx_products_catalog_order
    ON products (category_id, active, available, display_order, name);

CREATE TABLE product_option_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    minimum_selections INTEGER NOT NULL DEFAULT 0,
    maximum_selections INTEGER NOT NULL DEFAULT 1,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_option_groups_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT chk_product_option_groups_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_product_option_groups_selections
        CHECK (
            minimum_selections >= 0
            AND maximum_selections >= 1
            AND maximum_selections >= minimum_selections
        ),
    CONSTRAINT chk_product_option_groups_display_order
        CHECK (display_order >= 0),
    CONSTRAINT chk_product_option_groups_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_product_option_groups_product_name_ci
    ON product_option_groups (product_id, lower(name));

CREATE INDEX idx_product_option_groups_catalog_order
    ON product_option_groups (product_id, active, display_order, name);

CREATE TABLE product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_group_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    additional_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_options_group
        FOREIGN KEY (option_group_id)
        REFERENCES product_option_groups(id) ON DELETE RESTRICT,
    CONSTRAINT chk_product_options_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_product_options_additional_price
        CHECK (additional_price >= 0),
    CONSTRAINT chk_product_options_display_order
        CHECK (display_order >= 0),
    CONSTRAINT chk_product_options_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_product_options_group_name_ci
    ON product_options (option_group_id, lower(name));

CREATE INDEX idx_product_options_catalog_order
    ON product_options (option_group_id, active, display_order, name);

CREATE TABLE stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    unit VARCHAR(30) NOT NULL,
    current_stock NUMERIC(15, 3) NOT NULL DEFAULT 0,
    minimum_stock NUMERIC(15, 3) NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_stock_items_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT chk_stock_items_description
        CHECK (description IS NULL OR btrim(description) <> ''),
    CONSTRAINT chk_stock_items_unit
        CHECK (unit IN ('KG', 'G', 'L', 'ML', 'UN', 'CX', 'PACKAGE', 'TRAY')),
    CONSTRAINT chk_stock_items_balances
        CHECK (current_stock >= 0 AND minimum_stock >= 0),
    CONSTRAINT chk_stock_items_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_stock_items_name_ci
    ON stock_items (lower(name));

CREATE INDEX idx_stock_items_active_name
    ON stock_items (active, name);

CREATE INDEX idx_stock_items_alerts
    ON stock_items (active, current_stock, minimum_stock);

CREATE TABLE product_stock_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    stock_item_id BIGINT NOT NULL,
    quantity_per_sale NUMERIC(15, 3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_stock_links_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_stock_links_stock_item
        FOREIGN KEY (stock_item_id) REFERENCES stock_items(id) ON DELETE RESTRICT,
    CONSTRAINT chk_product_stock_links_quantity
        CHECK (quantity_per_sale > 0),
    CONSTRAINT chk_product_stock_links_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_product_stock_links_active_product
    ON product_stock_links (product_id)
    WHERE active = TRUE;

CREATE INDEX idx_product_stock_links_stock_item
    ON product_stock_links (stock_item_id, active);

CREATE TABLE cash_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    opened_by_user_id BIGINT NOT NULL,
    opened_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opening_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
    closed_by_user_id BIGINT,
    closed_at TIMESTAMP WITHOUT TIME ZONE,
    expected_cash NUMERIC(12, 2),
    counted_cash NUMERIC(12, 2),
    difference_amount NUMERIC(12, 2),
    closing_note VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cash_shifts_opened_by_user
        FOREIGN KEY (opened_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cash_shifts_closed_by_user
        FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_cash_shifts_status
        CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT chk_cash_shifts_opening_balance
        CHECK (opening_balance >= 0),
    CONSTRAINT chk_cash_shifts_counted_cash
        CHECK (counted_cash IS NULL OR counted_cash >= 0),
    CONSTRAINT chk_cash_shifts_closing_note
        CHECK (closing_note IS NULL OR btrim(closing_note) <> ''),
    CONSTRAINT chk_cash_shifts_lifecycle
        CHECK (
            (
                status = 'OPEN'
                AND closed_by_user_id IS NULL
                AND closed_at IS NULL
                AND expected_cash IS NULL
                AND counted_cash IS NULL
                AND difference_amount IS NULL
            )
            OR
            (
                status = 'CLOSED'
                AND closed_by_user_id IS NOT NULL
                AND closed_at IS NOT NULL
                AND closed_at >= opened_at
                AND expected_cash IS NOT NULL
                AND counted_cash IS NOT NULL
                AND difference_amount = counted_cash - expected_cash
            )
        ),
    CONSTRAINT chk_cash_shifts_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_cash_shifts_single_open
    ON cash_shifts ((1))
    WHERE status = 'OPEN';

CREATE INDEX idx_cash_shifts_opened_at
    ON cash_shifts (opened_at DESC);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    restaurant_table_id BIGINT,
    table_number_snapshot INTEGER,
    customer_name VARCHAR(120),
    customer_phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    service_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    opened_by_user_id BIGINT NOT NULL,
    opened_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_by_user_id BIGINT,
    closed_at TIMESTAMP WITHOUT TIME ZONE,
    closed_business_date DATE,
    cancelled_by_user_id BIGINT,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    cancellation_reason VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sales_restaurant_table
        FOREIGN KEY (restaurant_table_id)
        REFERENCES restaurant_tables(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_opened_by_user
        FOREIGN KEY (opened_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_closed_by_user
        FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_cancelled_by_user
        FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_sales_type
        CHECK (type IN ('TABLE', 'COUNTER')),
    CONSTRAINT chk_sales_status
        CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED')),
    CONSTRAINT chk_sales_origin
        CHECK (
            (
                type = 'TABLE'
                AND restaurant_table_id IS NOT NULL
                AND table_number_snapshot IS NOT NULL
                AND table_number_snapshot > 0
            )
            OR
            (
                type = 'COUNTER'
                AND restaurant_table_id IS NULL
                AND table_number_snapshot IS NULL
            )
        ),
    CONSTRAINT chk_sales_customer_name
        CHECK (customer_name IS NULL OR btrim(customer_name) <> ''),
    CONSTRAINT chk_sales_customer_phone
        CHECK (customer_phone IS NULL OR btrim(customer_phone) <> ''),
    CONSTRAINT chk_sales_amounts
        CHECK (
            service_fee >= 0
            AND discount_amount >= 0
        ),
    CONSTRAINT chk_sales_lifecycle
        CHECK (
            (
                status = 'OPEN'
                AND closed_by_user_id IS NULL
                AND closed_at IS NULL
                AND closed_business_date IS NULL
                AND cancelled_by_user_id IS NULL
                AND cancelled_at IS NULL
                AND cancellation_reason IS NULL
            )
            OR
            (
                status = 'CLOSED'
                AND closed_by_user_id IS NOT NULL
                AND closed_at IS NOT NULL
                AND closed_at >= opened_at
                AND closed_business_date IS NOT NULL
                AND cancelled_by_user_id IS NULL
                AND cancelled_at IS NULL
                AND cancellation_reason IS NULL
            )
            OR
            (
                status = 'CANCELLED'
                AND closed_by_user_id IS NULL
                AND closed_at IS NULL
                AND closed_business_date IS NULL
                AND cancelled_by_user_id IS NOT NULL
                AND cancelled_at IS NOT NULL
                AND cancelled_at >= opened_at
                AND cancellation_reason IS NOT NULL
                AND btrim(cancellation_reason) <> ''
            )
        ),
    CONSTRAINT chk_sales_timestamps
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_sales_one_open_per_table
    ON sales (restaurant_table_id)
    WHERE type = 'TABLE' AND status = 'OPEN';

CREATE INDEX idx_sales_open_operation
    ON sales (status, type, opened_at DESC);

CREATE INDEX idx_sales_table_history
    ON sales (restaurant_table_id, opened_at DESC, id DESC)
    WHERE restaurant_table_id IS NOT NULL;

CREATE INDEX idx_sales_closed_reports
    ON sales (status, closed_business_date, type, closed_at, id);

CREATE INDEX idx_sales_cancelled_at
    ON sales (cancelled_at)
    WHERE status = 'CANCELLED';

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(120) NOT NULL,
    -- The application stores 'Sem categoria' when products.category_id is NULL.
    category_name_snapshot VARCHAR(120) NOT NULL,
    base_unit_price_snapshot NUMERIC(12, 2) NOT NULL,
    unit_price_snapshot NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    notes VARCHAR(500),
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    cancelled_by_user_id BIGINT,
    cancellation_reason VARCHAR(500),

    CONSTRAINT fk_sale_items_sale
        FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_items_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_items_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_items_cancelled_by_user
        FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_sale_items_product_snapshot
        CHECK (btrim(product_name_snapshot) <> ''),
    CONSTRAINT chk_sale_items_category_snapshot
        CHECK (btrim(category_name_snapshot) <> ''),
    CONSTRAINT chk_sale_items_prices
        CHECK (
            base_unit_price_snapshot >= 0
            AND unit_price_snapshot >= base_unit_price_snapshot
            AND subtotal >= 0
        ),
    CONSTRAINT chk_sale_items_quantity
        CHECK (quantity > 0),
    CONSTRAINT chk_sale_items_subtotal
        CHECK (subtotal = unit_price_snapshot * quantity),
    CONSTRAINT chk_sale_items_notes
        CHECK (notes IS NULL OR btrim(notes) <> ''),
    CONSTRAINT chk_sale_items_cancellation
        CHECK (
            (
                cancelled_at IS NULL
                AND cancelled_by_user_id IS NULL
                AND cancellation_reason IS NULL
            )
            OR
            (
                cancelled_at IS NOT NULL
                AND cancelled_at >= created_at
                AND cancelled_by_user_id IS NOT NULL
                AND cancellation_reason IS NOT NULL
                AND btrim(cancellation_reason) <> ''
            )
        )
);

CREATE INDEX idx_sale_items_active_by_sale
    ON sale_items (sale_id, created_at, id)
    WHERE cancelled_at IS NULL;

CREATE INDEX idx_sale_items_product_reports
    ON sale_items (product_id, sale_id)
    WHERE cancelled_at IS NULL;

CREATE INDEX idx_sale_items_cancelled_at
    ON sale_items (cancelled_at)
    WHERE cancelled_at IS NOT NULL;

CREATE TABLE sale_item_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_item_id BIGINT NOT NULL,
    product_option_id BIGINT,
    option_group_name_snapshot VARCHAR(120) NOT NULL,
    option_name_snapshot VARCHAR(120) NOT NULL,
    additional_price_snapshot NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_item_options_sale_item
        FOREIGN KEY (sale_item_id) REFERENCES sale_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_item_options_product_option
        FOREIGN KEY (product_option_id)
        REFERENCES product_options(id) ON DELETE SET NULL,
    CONSTRAINT chk_sale_item_options_group_snapshot
        CHECK (btrim(option_group_name_snapshot) <> ''),
    CONSTRAINT chk_sale_item_options_name_snapshot
        CHECK (btrim(option_name_snapshot) <> ''),
    CONSTRAINT chk_sale_item_options_price
        CHECK (additional_price_snapshot >= 0)
);

CREATE INDEX idx_sale_item_options_sale_item
    ON sale_item_options (sale_item_id, id);

CREATE UNIQUE INDEX uq_sale_item_options_selected_option
    ON sale_item_options (sale_item_id, product_option_id)
    WHERE product_option_id IS NOT NULL;

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    cash_shift_id BIGINT,
    method VARCHAR(30) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    received_by_user_id BIGINT NOT NULL,
    paid_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_sale
        FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_cash_shift
        FOREIGN KEY (cash_shift_id) REFERENCES cash_shifts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_received_by_user
        FOREIGN KEY (received_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_payments_method
        CHECK (method IN ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'PIX', 'VOUCHER')),
    CONSTRAINT chk_payments_amount
        CHECK (amount > 0),
    CONSTRAINT chk_payments_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_payments_sale_time
    ON payments (sale_id, paid_at, id);

CREATE INDEX idx_payments_cash_shift_time
    ON payments (cash_shift_id, paid_at, id);

CREATE INDEX idx_payments_paid_at
    ON payments (paid_at);

CREATE TABLE cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_shift_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    note VARCHAR(500) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cash_movements_shift
        FOREIGN KEY (cash_shift_id) REFERENCES cash_shifts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cash_movements_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_cash_movements_type
        CHECK (type IN ('SUPPLY', 'WITHDRAWAL')),
    CONSTRAINT chk_cash_movements_amount
        CHECK (amount > 0),
    CONSTRAINT chk_cash_movements_note_not_blank
        CHECK (btrim(note) <> ''),
    CONSTRAINT chk_cash_movements_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_cash_movements_shift_time
    ON cash_movements (cash_shift_id, occurred_at, id);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    delta_quantity NUMERIC(15, 3) NOT NULL,
    previous_balance NUMERIC(15, 3) NOT NULL,
    resulting_balance NUMERIC(15, 3) NOT NULL,
    sale_item_id BIGINT,
    reversed_movement_id BIGINT,
    reason VARCHAR(500),
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_movements_stock_item
        FOREIGN KEY (stock_item_id) REFERENCES stock_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_movements_sale_item
        FOREIGN KEY (sale_item_id) REFERENCES sale_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_movements_reversed_movement
        FOREIGN KEY (reversed_movement_id)
        REFERENCES stock_movements(id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_movements_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT uq_stock_movements_reversed_movement
        UNIQUE (reversed_movement_id),
    CONSTRAINT chk_stock_movements_type
        CHECK (type IN ('ENTRY', 'SALE', 'SALE_REVERSAL', 'EXIT', 'LOSS', 'ADJUSTMENT')),
    CONSTRAINT chk_stock_movements_delta_direction
        CHECK (
            (type IN ('ENTRY', 'SALE_REVERSAL') AND delta_quantity > 0)
            OR (type IN ('SALE', 'EXIT', 'LOSS') AND delta_quantity < 0)
            OR (type = 'ADJUSTMENT' AND delta_quantity <> 0)
        ),
    CONSTRAINT chk_stock_movements_balances
        CHECK (
            previous_balance >= 0
            AND resulting_balance >= 0
            AND resulting_balance = previous_balance + delta_quantity
        ),
    CONSTRAINT chk_stock_movements_origin
        CHECK (
            (
                type = 'SALE'
                AND sale_item_id IS NOT NULL
                AND reversed_movement_id IS NULL
            )
            OR
            (
                type = 'SALE_REVERSAL'
                AND sale_item_id IS NOT NULL
                AND reversed_movement_id IS NOT NULL
            )
            OR
            (
                type IN ('ENTRY', 'EXIT', 'LOSS', 'ADJUSTMENT')
                AND sale_item_id IS NULL
                AND reversed_movement_id IS NULL
            )
        ),
    CONSTRAINT chk_stock_movements_not_self_reversal
        CHECK (reversed_movement_id IS NULL OR reversed_movement_id <> id),
    CONSTRAINT chk_stock_movements_reason
        CHECK (
            (reason IS NULL OR btrim(reason) <> '')
            AND (
                type NOT IN ('LOSS', 'ADJUSTMENT')
                OR (reason IS NOT NULL AND btrim(reason) <> '')
            )
        )
);

CREATE UNIQUE INDEX uq_stock_movements_sale_per_item
    ON stock_movements (sale_item_id)
    WHERE type = 'SALE';

CREATE INDEX idx_stock_movements_stock_item_time
    ON stock_movements (stock_item_id, created_at DESC, id DESC);

CREATE INDEX idx_stock_movements_type_time
    ON stock_movements (type, created_at DESC, id DESC);

CREATE INDEX idx_stock_movements_sale_item
    ON stock_movements (sale_item_id, created_at, id)
    WHERE sale_item_id IS NOT NULL;

-- Cross-table invariants intentionally remain in transactional services:
-- 1. subtotal_amount is derived from the sum of active sale_items;
-- 2. item option selections respect each active group's minimum and maximum;
-- 3. item unit price equals base price plus selected option snapshots;
-- 4. final_amount is derived from subtotal, service_fee and discount_amount;
-- 5. paid_amount and remaining_amount are derived from SUM(payments.amount);
-- 6. SUM(payments.amount) never exceeds the derived final_amount;
-- 7. sale items cannot be altered or cancelled after the first payment;
-- 8. a sale with payments cannot be cancelled without a financial reversal flow;
-- 9. CLOSED sales have exact payment and at least one active item;
-- 10. zero-value COUNTER sales do not close automatically;
-- 11. stock movement reversal targets a SALE for the same item and stock item;
-- 12. operational payments use the currently OPEN cash shift;
-- 13. closed/cancelled sales and ledger records are immutable.
